//const ethers = require("ethers");
const path = require("path"); // This line imports the 'path' module
const { ethers } = require("hardhat");

async function listSigners() {
  const signers = await ethers.getSigners();
  console.log("Accounts:");
  signers.forEach((signer, index) => {
    console.log(`${index}: ${signer.address}`);
  });
}

listSigners().catch(console.error);

async function commitToContract(secret, contract, user) {
  // Generate the commitment hash
  const commitment = ethers.utils.keccak256(ethers.utils.toUtf8Bytes(secret));

  // Send the commit transaction
  const tx = await contract.commit(commitment, { from: user });
  await tx.wait(); // Wait for the transaction to be mined

  console.log("Commitment:", commitment);
  console.log("Transaction Hash:", tx.hash);
}

// Testnet Sepolia
// const provider = new ethers.providers.JsonRpcProvider(
//   "https://eth-sepolia.g.alchemy.com/v2/SJA2I4mbcg2gqhNBSW9v6mjxyvm7BaT_"
// );

// const walletAddress = "0xBBe2ded2c9E0C8B6f0D36ab8e533509f98Ce05aF";

// // Load user's wallet
// const privateKey =
//   "89e4e04ecc424d1ae6b38028b631ca45d84da36d6b444441c5345ac372f1e27b"; // Replace with the user's private key
// const wallet = new ethers.Wallet(privateKey, provider);

// const walletAddress = "0xBBe2ded2c9E0C8B6f0D36ab8e533509f98Ce05aF";

// Deployed contract address and ABI
// const walletAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";
const walletAddress = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8";
const contractAddress = "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0";

const privateKey =
  //"0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"; // Replace with the user's private key
  "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";
// Load the ABI from the JSON file generated by Hardhat
// Define the path to the JSON artifact file (adjusting for correct relative path)
const contractArtifactPath = path.join(
  __dirname,
  "..", // Go up one level to the project root
  "artifacts",
  "contracts",
  "MerkleTreeBit.sol",
  "MerkleTreeBit.json"
);

// Check if the path exists (for debugging purposes)
console.log("Contract artifact path:", contractArtifactPath);

// Require the contract ABI from the JSON artifact
const contractArtifact = require(contractArtifactPath);
const contractABI = contractArtifact.abi;

// Connect to the local Hardhat network
const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545"); // Correct provider constructor

const wallet = new ethers.Wallet(privateKey, provider);

// Optionally, use the first account (provided by Hardhat) to interact with the contract
const signer = provider.getSigner(); // Get the first account from Hardhat's local node

// Create a contract instance: with wallet or signer
const contract = new ethers.Contract(contractAddress, contractABI, wallet);
//const contract = new ethers.Contract(contractAddress, contractABI, signer);

// Overview of Commit-Reveal Mechanism
// Commit Phase:
// Users submit a hash of their secret (e.g., a random number or phrase) along with their desired actions (like minting an NFT).
// The hash ensures that users cannot change their secret later.
// Reveal Phase:
// After 10 blocks, users reveal their secret.
// The contract verifies the hash and calculates a random NFT ID using the secret, combined with on-chain randomness (e.g., block hash).

// Function to Commit a secret
async function createCommitment(secret, userAddress) {
  // Generate a hash from the secret and user's address
  // const commitment = ethers.utils.keccak256(
  //   ethers.utils.defaultAbiCoder.encode(
  //     ["string", "address"],
  //     [secret, userAddress]
  //   )
  // );

  const commitment = ethers.utils.keccak256(
    ethers.utils.solidityPack(["string", "address"], [secret, userAddress])
  );

  console.log("Generated Commitment Hash:", commitment);
  return commitment;
}

// Example usage
(async () => {
  const secret = "my_super_secret"; // User-provided secret
  const userAddress = walletAddress; // Replace with the user's address
  console.log("User address used for commit:" + userAddress);

  // Generate the commitment hash
  const commitmentHash = await createCommitment(secret, userAddress);

  console.log("Commitment Hash:", commitmentHash);
})();

async function listAccounts() {
  const signers = await ethers.getSigners();
  console.log("Accounts:");
  signers.forEach((signer, index) => {
    console.log(`${index}: ${signer.address}`);
  });
}

listAccounts().catch(console.error);

// The reveal function in the smart contract will handle the
// user's submission of their secret and validate it against
//the previously submitted commitment. This ensures fairness and randomness in allocating NFT IDs.
