// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

// AutomationCompatible.sol imports the functions from both ./AutomationBase.sol and
// ./interfaces/AutomationCompatibleInterface.sol
import {AutomationCompatibleInterface} from "@chainlink/contracts@1.2.0/src/v0.8/automation/AutomationCompatible.sol";

// Counter example, see https://docs.chain.link/chainlink-automation/guides/compatible-contracts
// 1. Compile and deploy contract: 0xeBFFa6B58858a4198c79FA26Bc07A2A626BF6E81
// 2. Register contract address at: https://automation.chain.link/arbitrum-sepolia
// Set interval with cron:
// A cron expression typically has the following format:

// scss
// Copy code
// * * * * *
// │ │ │ │ │
// │ │ │ │ └── Day of the Week (0 - 6) (Sunday=0)
// │ │ │ └──── Month (1 - 12)
// │ │ └────── Day of the Month (1 - 31)
// │ └──────── Hour (0 - 23)
// └────────── Minute (0 - 59)

// We use for 1 minute: */1 * * * *

// Save CA and use in frontend to access the functions below

contract Counter is AutomationCompatibleInterface {
    /**
     * Public counter variable
     */
    uint256 public counter;

    /**
     * Use an interval in seconds and a timestamp to slow execution of Upkeep
     */
    uint256 public immutable interval;
    uint256 public lastTimeStamp;

    constructor(uint256 updateInterval) {
        interval = updateInterval;
        lastTimeStamp = block.timestamp;

        counter = 0;
    }

    function checkUpkeep(
        bytes calldata /* checkData */
    )
        external
        view
        override
        returns (bool upkeepNeeded, bytes memory /* performData */)
    {
        upkeepNeeded = (block.timestamp - lastTimeStamp) > interval;
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        if ((block.timestamp - lastTimeStamp) > interval) {
            lastTimeStamp = block.timestamp;
            counter = counter + 1;
        }
        // We don't use the performData in this example. The performData is generated by the Automation Node's call to your checkUpkeep function
    }
}
